<a href="https://colab.research.google.com/github/mahdid-lilia/CLA-BOOTCAMP/blob/master/Unit%204/Homeworks/ComputationGraphs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import tensorflow as tf
import timeit

In [35]:
def eager_sigmoid_function(x):
  return 1/(1+tf.math.exp(-x))

In [36]:
x= tf.random.uniform([10])
eager_sigmoid_function(x)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.64246744, 0.54139656, 0.7095581 , 0.57526755, 0.7241431 ,
       0.6812413 , 0.5880391 , 0.5361345 , 0.582012  , 0.66122603],
      dtype=float32)>

In [37]:
graph_sigmoid_function= tf.function(eager_sigmoid_function)

In [38]:
graph_sigmoid_function(x)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.64246744, 0.54139656, 0.7095581 , 0.57526755, 0.7241431 ,
       0.6812413 , 0.5880391 , 0.5361345 , 0.582012  , 0.66122603],
      dtype=float32)>

In [39]:
print("Eager time:", timeit.timeit(lambda: eager_sigmoid_function(x), number=100))
print("Graph time:", timeit.timeit(lambda: graph_sigmoid_function(x), number=100))


Eager time: 0.02451513999949384
Graph time: 0.04187623899997561


We noticed that Eager mode is faster, this is because of the time that the graphic construction takes 

In [40]:
from tensorflow.keras import Sequential, Model 
from tensorflow.keras.layers import Flatten, Dense 
model= Sequential ([
                    Flatten(input_shape=(28,28)),
                    Dense(512, activation='relu'),
                    Dense(256, activation='relu'),
                    Dense(128, activation='relu'),
                    Dense(64, activation='relu'),
                    Dense(32, activation='relu'),
                    Dense(10, activation='softmax'),
])
input_data= tf.random.uniform([1000,28,28])
eager_model= model
eager_time= timeit.timeit(lambda:eager_sigmoid_function(input_data), number=1000)
print('Eager time:', eager_time)

graph_model=tf.function(eager_model)
graph_time=timeit.timeit(lambda: graph_model(input_data), number=1000)
print('Graph time:', graph_time)

faster="Graph" if graph_time<eager_time else "Eager"
speedup= eager_time/graph_time if graph_time< eager_time else graph_time/eager_time 
print(faster, 'execution mode was', speedup , 'x faster!')

Eager time: 3.043871554999896
Graph time: 19.688165248000587
Eager execution mode was 6.468132735647336 x faster!
